#
# Module manifest for module 'Azure AD Support Manifest'
#
# Generated by: Max Vaughn
#
# Generated on: 12/14/2022
#

@{

# Script module or binary module file associated with this manifest
RootModule = '.\_RootModuleShared.psm1'

# Version number of this module.
ModuleVersion = '0.0.0'

# ID used to uniquely identify this module
GUID = '602d8568-3456-4a88-9f1b-c133d8d92753'

# Author of this module
Author = 'Max Vaughn'

# Company or vendor of this module
CompanyName = 'Max Vaughn'

# Copyright statement for this module
Copyright = '(c) 2019 Max Vaughn'

# Description of the functionality provided by this module
Description = 'PowerShell module that wraps Azure DevOps REST APIs.'

# Minimum version of the Windows PowerShell engine required by this module
# PowerShellVersion = ''

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of the .NET Framework required by this module
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @("AzureAdPreview")

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module
ScriptsToProcess = @("_startup.ps1")

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
NestedModules = @(
    ".\functions\Add-ADOLinkItem.ps1",
".\functions\Get-ADOContext.ps1",
".\functions\Get-ADOOperationJSON.ps1",
".\functions\Get-ADOOrganizationBaseUrl.ps1",
".\functions\Get-ADOProcessTemplates.ps1",
".\functions\Get-ADOProjectId.ps1",
".\functions\Get-ADOProjects.ps1",
".\functions\Get-ADOUrl.ps1",
".\functions\Get-GitItems.ps1",
".\functions\Get-PageStatsFromCSV.ps1",
".\functions\Get-WikiFolderDocs.ps1",
".\functions\Get-WikiPage.ps1",
".\functions\Get-WikiPageIdFromTagPage.ps1",
".\functions\Get-WikiPageList.ps1",
".\functions\Get-WikiPages.ps1",
".\functions\Get-WikiPageStats.ps1",
".\functions\Get-Wikis.ps1",
".\functions\Get-WorkItemById.ps1",
".\functions\Invoke-RestMethodWithPaging.ps1",
".\functions\New-ADOCreateOperation.ps1",
".\functions\New-ADOWorkItem.ps1",
".\functions\New-ReplacementItem.ps1",
".\functions\New-WorkItemsFromWikiPages.ps1",
".\functions\Remove-Repo.ps1",
".\functions\Remove-Wiki.ps1",
".\functions\Set-ADOAuthHeaders.ps1",
".\functions\Set-ADOGlobals.ps1",
".\functions\Update-WikiPage.ps1"
".\functions\Write-DebugInfo.ps1",
".\functions\Write-DebugObject.ps1"
)

# Functions to export from this module
FunctionsToExport = @(
    "Add-ADOLinkItem",
"Get-ADOContext",
"Get-ADOOperationJSON",
"Get-ADOOrganizationBaseUrl",
"Get-ADOProcessTemplates",
"Get-ADOProjectId",
"Get-ADOProjects",
"Get-ADOUrl",
"Get-GitItems",
"Get-PageStatsFromCSV",
"Get-WikiFolderDocs",
"Get-WikiPage",
"Get-WikiPageIdFromTagPage",
"Get-WikiPageList",
"Get-WikiPages",
"Get-WikiPageStats",
"Get-Wikis",
"Get-WorkItemById",
"Invoke-RestMethodWithPaging",
"New-ADOCreateOperation",
"New-ADOWorkItem",
"New-ReplacementItem",
"New-WorkItemsFromWikiPages",
"Remove-Repo",
"Remove-Wiki",
"Set-ADOAuthHeaders",
"Set-ADOGlobals",
"Update-WikiPage",
"Write-DebugInfo",
"Write-DebugObject"
)

# Cmdlets to export from this module
CmdletsToExport = '*-ADO*'

# Variables to export from this module
VariablesToExport = ''

# Aliases to export from this module
AliasesToExport = '*-ADO*'

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess
# PrivateData = ''

# HelpInfo URI of this module
HelpInfoURI = 'https://github.com/max-vaughn/ADO-API-Powershell-Module'

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}
